// <auto-generated />
namespace SnowFur.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class MaxlengthForConventionName : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MaxlengthForConventionName));
        
        string IMigrationMetadata.Id
        {
            get { return "201610130108008_MaxlengthForConventionName"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
